In [1]:
from keras.models import Sequential #YSA modelini kullanmak için
import pandas as pd
from sklearn.model_selection import train_test_split
from textblob import TextBlob
import pandas as pd
from spacy.tokenizer import Tokenizer
from spacy.lang.tr import Turkish
from tqdm import tqdm
from wordcloud import WordCloud
import matplotlib.pyplot as plt
from sklearn import preprocessing
from sklearn.feature_extraction.text import TfidfVectorizer
import numpy as np

Using TensorFlow backend.


In [5]:
data = pd.read_csv('lemessi10.csv')
data

tweet
0      leo messi cristiano special competition among ...
1                                   poles stop leo messi
2      la liga goal assist king champions league top ...
3      leo messi became first player score goal diffe...
4                    come tomorrow start work fenerbahçe
...                                                  ...
20099  via drawing lionel messi art lionelmessi barce...
20100  lionel messi made funny comment allegations ma...
20101  lionelmessi dont worry messi father go jail gi...
20102               lionel messi without detonating bomb
20103            lionel messi lottery offer galatasaraya

[20104 rows x 1 columns]

In [6]:
def getSubjectivity(text):
    return TextBlob(text).sentiment.subjectivity

def getPolarity(text):
    return TextBlob(text).sentiment.polarity

data['Subjectivity'] = data['tweet'].apply(getSubjectivity)
data['Polarity'] = data['tweet'].apply(getPolarity)

data

tweet  Subjectivity  \
0      leo messi cristiano special competition among ...      0.586190   
1                                   poles stop leo messi      0.000000   
2      la liga goal assist king champions league top ...      0.766667   
3      leo messi became first player score goal diffe...      0.466667   
4                    come tomorrow start work fenerbahçe      0.000000   
...                                                  ...           ...   
20099  via drawing lionel messi art lionelmessi barce...      0.000000   
20100  lionel messi made funny comment allegations ma...      1.000000   
20101  lionelmessi dont worry messi father go jail gi...      0.375000   
20102               lionel messi without detonating bomb      0.000000   
20103            lionel messi lottery offer galatasaraya      0.000000   

       Polarity  
0      0.225119  
1      0.000000  
2      0.200000  
3      0.125000  
4      0.000000  
...         ...  
20099  0.000000  
20100  0.250000  
20101 -0.050000  
20102  0.000000  
20103  0.000000  

[20104 rows x 3 columns]

In [7]:
def getAnalysis(score):
    if score<0:
        return 'Negative'
    elif score==0:
        return 'Neutral'
    else:
        return 'Positive'
    
data['Analysis'] = data['Polarity'].apply(getAnalysis)
data

tweet  Subjectivity  \
0      leo messi cristiano special competition among ...      0.586190   
1                                   poles stop leo messi      0.000000   
2      la liga goal assist king champions league top ...      0.766667   
3      leo messi became first player score goal diffe...      0.466667   
4                    come tomorrow start work fenerbahçe      0.000000   
...                                                  ...           ...   
20099  via drawing lionel messi art lionelmessi barce...      0.000000   
20100  lionel messi made funny comment allegations ma...      1.000000   
20101  lionelmessi dont worry messi father go jail gi...      0.375000   
20102               lionel messi without detonating bomb      0.000000   
20103            lionel messi lottery offer galatasaraya      0.000000   

       Polarity  Analysis  
0      0.225119  Positive  
1      0.000000   Neutral  
2      0.200000  Positive  
3      0.125000  Positive  
4      0.000000   Neutral  
...         ...       ...  
20099  0.000000   Neutral  
20100  0.250000  Positive  
20101 -0.050000  Negative  
20102  0.000000   Neutral  
20103  0.000000   Neutral  

[20104 rows x 4 columns]

In [8]:
label_enc = preprocessing.LabelEncoder().fit_transform(data['Analysis'])
print(label_enc)

[2 1 2 ... 0 1 1]


In [9]:
vect = TfidfVectorizer(analyzer='word',lowercase=False)
sent_vector = vect.fit_transform(data['tweet'])

print(sent_vector)

  (0, 4901)	0.24890649791616995
  (0, 8400)	0.2248843852005883
  (0, 9616)	0.3005265054293155
  (0, 10463)	0.26443682295436655
  (0, 10755)	0.12437836632510421
  (0, 10674)	0.3197556424753424
  (0, 7505)	0.2278590916842625
  (0, 7275)	0.23068237973977024
  (0, 5929)	0.23467514211515997
  (0, 6787)	0.22452939908218347
  (0, 11463)	0.2566928707888658
  (0, 3862)	0.2623376404230149
  (0, 13088)	0.16746638314826084
  (0, 513)	0.2594037296105074
  (0, 2752)	0.2533717944917551
  (0, 11704)	0.2371030045770058
  (0, 3021)	0.1715437410829645
  (0, 8023)	0.04858473815579372
  (0, 7227)	0.12901752474861564
  (1, 11908)	0.5178896470172775
  (1, 9848)	0.7899569787592855
  (1, 8023)	0.11568574755708025
  (1, 7227)	0.30720529460603546
  (2, 1170)	0.2186445418362964
  (2, 5348)	0.18889864998589814
  :	:
  (20100, 7616)	0.44798571528983555
  (20100, 12290)	0.16821154871745747
  (20100, 8023)	0.06011974980385498
  (20101, 6545)	0.4695915522642063
  (20101, 13604)	0.38123226179833347
  (20101, 4240)	0.31

In [22]:
x_train ,x_test,y_train,y_test = train_test_split(sent_vector,label_enc,test_size=0.2,random_state=0)
print(x_train)
print(x_test)

  (0, 13395)	0.7820676523303159
  (0, 9245)	0.21726746598062696
  (0, 13612)	0.47169029052023
  (0, 1251)	0.2836666959121212
  (0, 8023)	0.06888476967705373
  (0, 7227)	0.1829245729001043
  (1, 11025)	0.9528725138821527
  (1, 7384)	0.3033710142513728
  (2, 7519)	0.863764305801495
  (2, 1251)	0.24688941449136664
  (2, 3719)	0.42258604774585956
  (2, 8023)	0.11990776991465449
  (3, 5366)	0.3812544911608235
  (3, 4740)	0.45071958825275993
  (3, 13455)	0.3844921222235943
  (3, 1361)	0.306115174301755
  (3, 616)	0.3650088425035477
  (3, 5953)	0.303383621516964
  (3, 6169)	0.2876905171073275
  (3, 6862)	0.3070994229422668
  (3, 8023)	0.08721930766570057
  (4, 13827)	0.5296908594685955
  (4, 2006)	0.7102412702407066
  (4, 1361)	0.4459177545124203
  (4, 8023)	0.12705230282402943
  :	:
  (16081, 8951)	0.17353607365897503
  (16081, 8945)	0.19507789543467813
  (16081, 5139)	0.17353607365897503
  (16081, 8212)	0.1742365373153401
  (16081, 13742)	0.16667623004954044
  (16081, 7375)	0.11030480445694

In [23]:
from keras.utils import to_categorical

train_encoded = to_categorical(y_train)
test_encoded = to_categorical(y_test)
print(train_encoded)
print(test_encoded)

[[0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 ...
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]]
[[0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]
 ...
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]]


In [24]:
n_sent, n_vect = np.shape(x_train)
xx_train = np.reshape(x_train.toarray(),(n_sent,n_vect,1))

nn_sent,nn_vect = np.shape(x_test)
xx_test =np.reshape(x_test.toarray(),(nn_sent,nn_vect,1))

In [25]:
from keras.models import Sequential #YSA modelini kullanmak için
from keras.layers import Dense #YSA da katman oluşturma
import pandas as pd
from sklearn.model_selection import train_test_split

model = Sequential()

model.add(Dense(1,kernel_initializer='uniform',activation='relu',input_dim=1))

#ikinci katman
model.add(Dense(12,kernel_initializer='uniform',activation='relu'))#ilk parametre yapay sinir ağı hücresi
#üçüncü katman
model.add(Dense(8,kernel_initializer='uniform',activation='relu'))
#dördüncü katman
model.add(Dense(1,kernel_initializer='uniform',activation='relu'))#çıkış katmanı

In [26]:
model.compile(loss='categorical_crossentropy',optimizer='adam',metrics=['accuracy'])# model derleme

In [36]:
#eğitim
model.fit(x_train,y_train,batch_size=10,epochs=10,verbose=1)

ValueError: Error when checking input: expected dense_17_input to have shape (1,) but got array with shape (14056,)

In [ ]:
#değerlendirme

result=model.evaluate(X_train,y_train)

predict=model.predict(X_train)
predict=model.predict(X_test)